### ISSUE TITLE
Issue with loading CRON value for scheduling load job from airbyte to snowflake

### ISSUE THREAD

**Issue by BojanValcon** [airbytehq/terraform-provider-airbyte#10]
Hello,

I am trying to create a scheduled load for my data from the airbyte source to a snoflake destination but I am having issued with the CRON variable and its use.I get the error:

 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to airbyte_connection.mssql_snowflake_connection, provider "provider[\"registry.terraform.io/airbytehq/airbyte\"]" produced an unexpected new value:
│ .schedule.cron_expression: was cty.StringVal("0 0 12 * * ?"), but now cty.StringVal("0 0 12 * * ? UTC").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Do you have any more input for this issue? 
Regards,
Bojan

**Comment by ThomasRooney** [comment]
Hey @BojanValcon 

As a workaround, would you mind trying this to configure a cron expression of `0 0 12 * * ? UTC`? 

I'll see if I can get a fix put together for the root cause.

**Comment by BojanValcon** [comment]
Hey @ThomasRooney,
I tried this as well but it did not work. The error is as states:

│ {"type":"https://reference.airbyte.com/reference/errors","title":"bad-request","status":400,"detail":"The body of the request contains an invalid connection configuration. The
│ cron expression 0 0 12 * * ? UTC is not valid or is less than the one hour minimum. The seconds and minutes values cannot be `*`."}.

On a side note, are you aware if the normalization option that is available in the UI will be added to the terraform connection repo? It is the option that allows you to normalize the json data into the native destionatjon format - table in this case for snowflake. I cannot seem to find anything similar in the newest version in terraform.

Thanks for your help,
Bojan

**Comment by ThomasRooney** [comment]
> │ {"type":"[https://reference.airbyte.com/reference/errors","title":"bad-request","status":400,"detail":"The](https://reference.airbyte.com/reference/errors%22,%22title%22:%22bad-request%22,%22status%22:400,%22detail%22:%22The) body of the request contains an invalid connection configuration. The
│ cron expression 0 0 12 * * ? UTC is not valid or is less than the one hour minimum. The seconds and minutes values cannot be *."}.

This should be fixed now. The airbyte terraform provider expects a cron expression in a format alike `0 0 12 * * ? UTC`

> On a side note, are you aware if the normalization option that is available in the UI will be added to the terraform connection repo? It is the option that allows you to normalize the json data into the native destination format - table in this case for snowflake. I cannot seem to find anything similar in the newest version in terraform.

We're awaiting an OpenAPI spec update that will enable more of properties to be brought into the terraform provider (alongside getting resource import working), but I don't know the timeline.

**Comment by BojanValcon** [comment]
Thanks a lot!
