### ISSUE TITLE
airbyte_connection non_breaking_schema_updates_behavior lacks allowed values

### ISSUE THREAD

**Issue by lizdeika** [airbytehq/terraform-provider-airbyte#19]
`airbyte_connection` `non_breaking_schema_updates_behavior`
only supports
- ignore
- disable_connection

while airbyte api supports four values https://reference.airbyte.com/reference/createconnection 
- ignore
- disable_connection
- propagate_columns
- propagate_fully

Same in cloud UI, four values supported

**Comment by rileybrook** [comment]
We have deployed a solution for this, and verified it is working. Closing issue.
