### ISSUE TITLE
Cron Expression not evaluated properly in Connection resource

### ISSUE THREAD

**Issue by thatkellenguy** [airbytehq/terraform-provider-airbyte#29]
When attempting to create a connection, the cron expression is considered faulty when it should not be.  When I enter a cron expression greater than hourly, it continues to say that the cron expression is invalid. 

```
The cron expression 0 0 * * * is not valid or is less than the one hour minimum. 
The seconds and minutes values cannot be `*`."
```

As you can see from this response, it is evaluating that a cronjob of "daily" is actually _less_ than hourly.

**Comment by thatkellenguy** [comment]
I have now tried many different cron expressions and am unable to get one that does not respond with this.

**Comment by terencecho** [comment]
We use this version of cron expressions which requires 6 or 7 fields: http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html.

Understandably, the current error message we give out is incorrect and unhelpful, we will be updating it shortly to be correctly correlated with the problem and to include information about which implementation of cron we expect.

**Comment by nurikk-sa** [comment]
Can you try this syntax? It worked for me
```
  schedule = {
    schedule_type   = "cron"
    cron_expression = "0 1 * * * ? UTC"
  }
```

**Comment by terencecho** [comment]
I've edited the error message to be along the lines of 
```
 "The cron expression " + cronExpression + " is not valid. Error: " + errorMessage
            + ". Please check the cron expression format at https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html");
```

and should be released in the next version. Thanks for bringing up this issue!

**Comment by thatkellenguy** [comment]
That appears to have worked.  Of note, it'll send you a message if you don't include a timezone.  It tells you that it's going to default to UTC which is fine for my case.
