### ISSUE TITLE
Unable to download the TF provider version

### ISSUE THREAD

**Issue by msenmurugan** [airbytehq/terraform-provider-airbyte#38]
TF Version: 0.15.5

Plan: Airbyte OSS

```
terraform {
  required_version = ">= 0.15.5"
  required_providers {
    airbyte = {
      source  = "registry.terraform.io/airbytehq/airbyte"
      version = "0.3.4"
    }
  }
}
```

The above TF provider results in the following error. Can you please help in resolving this issue?

Finding airbytehq/airbyte versions matching "0.3.4"...
╷
│ Error: Incompatible provider version
│ 
│ No compatible versions of provider registry.terraform.io/airbytehq/airbyte were found.

**Comment by ThomasRooney** [comment]
`source` should be `"airbytehq/airbyte"`

Latest documentation should always be on https://registry.terraform.io/providers/airbytehq/airbyte/latest/docs under "Use Provider"

**Comment by msenmurugan** [comment]
Thanks. This can be closed
