### ISSUE TITLE
terraform: airbyte_source_postgres  documentation inconsistency

### ISSUE THREAD

**Issue by dboyadzhiev** [airbytehq/terraform-provider-airbyte#71]
Hi,

airbyte terraform provider version: [v0.3.7](https://registry.terraform.io/providers/airbytehq/airbyte/0.3.7/docs/resources/source_postgres)

According the example usage `ssl_mode` configuration could use `source_postgres_allow` but the [schema documentation](https://registry.terraform.io/providers/airbytehq/airbyte/0.3.7/docs/resources/source_postgres#nestedatt--configuration--ssl_mode) says it should be just `allow`. Also, terraform throws an error in case of `source_postgres_allow` parameter.

```
ssl_mode = {
    allow = {}
  }
```

It is the same with `tunnel_method` and its properties

**Comment by ThomasRooney** [comment]
Noted / fixed in the generator. Thanks for the report. This will be fixed on next generation/release.

**Comment by ThomasRooney** [comment]
fixed https://github.com/airbytehq/terraform-provider-airbyte/blob/main/docs/resources/source_postgres.md
