### ISSUE TITLE
Terraform provider support for self-hosted

### ISSUE THREAD

**Issue by imonacloud** [airbytehq/terraform-provider-airbyte#8]
Absolutely love that Airbyte has launched a terraform provider to help manage the state of airbyte via terraform. Are there any plans to add support for the self-hosted version?

**Comment by rileybrook** [comment]
Hey there 👋 

We have heard the request from others as well, but have not finalized a decision there yet. We are planning Q3 roadmaps over the next couple weeks, and will follow up here in a couple weeks with a decision 🙂

**Comment by imonacloud** [comment]
Thanks @rileybrook !

**Comment by philippeboyd** [comment]
@rileybrook how will this work for Custom Connectors? 
Would forking this repo and adding our own custom connector be the right solution? 
Would a generic solution from Airbyte be an appropriate option?
Thoughts?

**Comment by shashanksinghfd** [comment]
Does this blog post means its generally available now ?
https://airbyte.com/blog/airbytes-official-api-and-terraform-provider-now-in-open-source

**Comment by robertomczak** [comment]
Unfortunately there is no full comatibility in API

eg Create Destination attempt via Terraform:

10.4.106.93 - - [16/Aug/2023:16:38:46 +0000] "POST /api/v1/destinations HTTP/1.1" 404 17 "-" "speakeasy-sdk/terraform 0.3.2 2.84.3 1.0.0" "10.2.55.36"    

while valid API call for Airbyte 0.50.19 
│ 10.4.106.243 - airbyte [16/Aug/2023:16:40:17 +0000] "POST /api/v1/destinations/create HTTP/1.1" 200 916 "-" "Go-http-client/2.0" "10.2.55.36"

**Comment by mliner** [comment]
There is no example of setting up the provider to be used with OSS version. What should be the `server_url`? An API endpoint in webapp or api-server endoint? There is no auth in OSS version - should I trigger the terraform without username and pass? Even though this functionality was mentioned in the blogpost above as available it clearly seems that either documentation is missing some vital information or it is not fully functional yet.
Can somebody shed some light on this please?

**Comment by ceik** [comment]
@mliner  and anyone else stumbling on this:

`server_url = "http://airbyte.company.com:8006/v1"` works if your UI is at `http://airbyte.company.com:8000`. 

You'll need to upgrade to a very recent version though. This works for me in `0.50.27`, but did not work is a version that was just a few weeks old.

**Comment by rensoostenbachBL** [comment]
@ceik Did you do any portforwarding / custom networking in order to reach the API at `"http://airbyte.company.com:8006/v1"`?

In my case, I'm running Airbyte on Kubernetes and `"http://airbyte.company.com:8006/v1"` doesn't work. 

If I run `kubectl port-forward airbyte-airbyte-api-server-pod 8006:8006`, the following Terraform configuration `server_url = "http://localhost:8006/v1"` does work, but giving Terraform the web URL still doesn't work.

**Comment by jace-ys** [comment]
@rensoostenbachBL The `airbyte-api-server` pod is not exposed to the Internet by default so you need to configure ingress (on your preferred hostname) such that you can access the API server without port-forwarding.
